### ISSUE TITLE
no desktop after install nvidia-driver

### ISSUE THREAD

**Issue by kuboosoft** [UnitedRPMs/nvidia-driver#2]
"Hi guys, i little help need here, i made a fresh install of Fedora 24, then update and then install unitedrpm repo after that i tried to install nvidia-driver, it installs OK but then after i reboot i get no desktop"

(Looks that dkms not match the kernel version 4.6.3-300)

Any ideas? I miss something?﻿

**SOLVED I needed to install kernel-devel and then run sudo dkms autoinstall**

**BTW it should be intresting write some "wiki" to install NVIDIA, thx!**﻿

https://plus.google.com/u/0/108727918131989030219/posts/iV3QBhP1SXs

**Comment by paulcarroty** [comment]
We need a microhowto for each package.

**Comment by kuboosoft** [comment]
@paulcarroty This should be automatic, and avoid the user work without graphic environment..

**Comment by x11tete11x** [comment]
Hi guys, i do some test
1) Fresh Fedora 24 install
2) sudo dnf update -y
3) reboot
4) enable unitedrpm repo
5) sudo dnf install -y kernel-devel
6) sudo dnf install -y nvidia-driver
7) reboot
8) everything works as expected :D

So my conclusion is that kernel-devel should be a dependency of nvidia-driver

Then you just make sudo dnf install nvidia-driver , reboot and works good :D

**Comment by paulcarroty** [comment]
https://github.com/UnitedRPMs/nvidia-driver/commit/aca93146dd8ab19cd00143a46e402601b4ca09b1 was merged to repo.
