### ISSUE TITLE
[Request] can you update the nvidia driver to the last stable version (should be 367.35)?

### ISSUE THREAD

**Issue by valeriodean** [UnitedRPMs/nvidia-driver#3]
Actually, when upgrading, dnf ask me to remove the driver installed by rpmfusion (367) with an oldest driver provided by unitedrpms (364).

Thanks.

**Comment by leigh123linux** [comment]
This happens because unitedrpms epoch version is greater than the rpmfusion driver

https://github.com/UnitedRPMs/nvidia-driver/blob/master/nvidia-driver.spec#L34

If you want to use the rpmfusion driver you will need to disable unitedrpms repo  or  add a nvidia exclude to unitedrpms repo file.

**Comment by valeriodean** [comment]
I guess my english is far to be good, sorry.
I dind't ask why the version of unitedrpms is suggested above the rpmfusion version, despite it is more recent.
My request is about the possibility to update the version delivered by unitedrpms to the last one provided by nvidia.

**Comment by paulcarroty** [comment]
@valeriodean try to upgrade in near future.

@leigh123linux, it's possible with `dnf install package-1.2.3`

**Comment by paulcarroty** [comment]
Done.
