### ISSUE TITLE
lib32 (for wine, mainly)

### ISSUE THREAD

**Issue by valeriodean** [UnitedRPMs/nvidia-driver#4]
Hi,
I tried to install the 32 bit driver (alongside to the 64 bit ones) to be able to play with wine end sons, however it seems I don't find the right package:

[valerio@valerio-casa ~]$ sudo dnf install nvidia-driver-2:364.19-3.fc24.i686 --allowerasing
Last metadata expiration check: 0:37:10 ago on Sat Aug 27 00:15:16 2016.
Error: nothing provides xorg-x11-server-Xorg(x86-32) >= 1.16 needed by nvidia-driver-2:364.19-3.fc24.i686

what package I should install?

Thanks.

**Comment by paulcarroty** [comment]
Try

```
# dnf install nvidia-driver-370.23-1.fc24.i686.rpm
```

**Comment by valeriodean** [comment]
It seems that file (the i686 version) is not available:

[valerio@valerio-casa ~]$ sudo dnf install nvidia-driver-
nvidia-driver-2:364.19-2.fc24.i686
nvidia-driver-2:364.19-3.fc24.i686
nvidia-driver-2:364.19-3.fc24.x86_64
nvidia-driver-2:370.23-1.fc24.x86_64
nvidia-driver-cuda-2:364.19-2.fc24.i686
nvidia-driver-cuda-2:364.19-3.fc24.i686
nvidia-driver-cuda-2:364.19-3.fc24.x86_64
nvidia-driver-cuda-2:370.23-1.fc24.x86_64
nvidia-driver-cuda-libs-2:364.19-2.fc24.i686
nvidia-driver-cuda-libs-2:364.19-3.fc24.i686
nvidia-driver-cuda-libs-2:364.19-3.fc24.x86_64
nvidia-driver-cuda-libs-2:370.23-1.fc24.x86_64
nvidia-driver-devel-2:364.19-2.fc24.i686
nvidia-driver-devel-2:364.19-3.fc24.i686
nvidia-driver-devel-2:364.19-3.fc24.x86_64
nvidia-driver-devel-2:370.23-1.fc24.x86_64
nvidia-driver-libs-2:364.19-2.fc24.i686
nvidia-driver-libs-2:364.19-3.fc24.i686
nvidia-driver-libs-2:364.19-3.fc24.x86_64
nvidia-driver-libs-2:370.23-1.fc24.x86_64
nvidia-driver-NvFBCOpenGL-2:364.19-2.fc24.i686
nvidia-driver-NvFBCOpenGL-2:364.19-3.fc24.i686
nvidia-driver-NvFBCOpenGL-2:364.19-3.fc24.x86_64
nvidia-driver-NvFBCOpenGL-2:370.23-1.fc24.x86_64
nvidia-driver-NVML-2:364.19-2.fc24.i686
nvidia-driver-NVML-2:364.19-3.fc24.i686
nvidia-driver-NVML-2:364.19-3.fc24.x86_64
nvidia-driver-NVML-2:370.23-1.fc24.x86_64
nvidia-driver-NVML-devel-1:352.79-2.fc24.x86_64

**Comment by paulcarroty** [comment]
Clean the dnf cache and try again.

**Comment by valeriodean** [comment]
Yeah, it works.
Only note that the package you need is only the libs one, not the driver i686, so the following one (and its dependency) is enough:
nvidia-driver-libs-2:370.23-1.fc24.i686

Thanks!
